### ISSUE TITLE
Fetching customer via user instead of order

### ISSUE THREAD

**Issue by loevgaard** [Setono/SyliusTrustpilotPlugin#3]
Why are you fetching the customer via the shop user instead of the order here: https://github.com/Setono/SyliusTrustpilotPlugin/blob/master/src/Trustpilot/Order/EligibilityChecker/ClientsTrustpilotEnabledOrderEligibilityChecker.php#L19 ?

**Comment by igormukhingmailcom** [comment]
You're right. My fault :)
